### ISSUE TITLE
New Pixiv system breaks the Pixiv tool

### ISSUE THREAD

**Issue by tonyz723** [anekos/Ank-Pixiv-Tool#120]
The new update to the Pixiv website seems to be incompatible with the current Pixiv tool. And update to fix compatibility would be appreciated!

At the moment, clicking the Pixiv tool download button sends the user to Pixiv's home page, and doesn't begin to download the image.

**Comment by kitoxel** [comment]
Since Pixiv released Whitecube the tool does indeed not detect the media anymore.

Maybe the developer can give us a hint if there will be an update. As an alternative for this tool the command-line-based tool 'Pixiv-Downloader' can be used to batch-download images. Unfortunately there's no browser integration available.

**Comment by winiah** [comment]
Now (2016.11.10) you can back to the CLASSICAL layout (with original URL), and continue using Ank Pixiv Tool.

https://twitter.com/winiah/status/796716743620071424
"この度、旧来の表示と現在の表示を切り替えられるよう変更いたしました。ページ下部の「以前のpixivを利用」ボタンより切り替えを行うことが可能です。"
