### ISSUE TITLE
Long filename means the image will fail to download

### ISSUE THREAD

**Issue by Tvtossen** [anekos/Ank-Pixiv-Tool#165]
- 発生した問題の詳細/Trouble details
When giving a filename that's too long, the add-on will be unable to download the image.
This has especially become an issue now that the ?tag? saves the romaji, meaning the filename could get insanely long.
While I would like for it to cut off automatically at 205 characters (the limit for a filename I believe), it'd also be nice if ? short-tags ? would take the first 5 tags since right now I think it only takes 1.

- 発生したURL/URL
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=62485215
(example link)

- 再現手順/Steps to reproduce
Filename:
?member-id? ?memoized-name? ?illust-id? ?illust-year?-?illust-month? ?title? ?tags?

- Ank Pixiv Toolのバージョン/Ank Pixiv Tool Version
3.0.4

- ブラウザのバージョン/Browser Version
Firefox 59.0.2 (64-bit)

Love what you do by the way

**Comment by ginzu** [comment]
I was able to reproduce it.
問題を再現できました。

I want to fix it by the end of May.
５月中にはなんとかしたいです…。

**Comment by ginzu** [comment]
This problem will be related to Windows MAX_PATH(=260) Limitation.
ファイル名の長さの問題は、FirefoxがWindowsのMAX_PATH定義(=260)をどう取り扱っているかにかかわる問題のようです。

It seems necessary to consider byte length, not charactor length.
文字列長(String.length)を260Char未満にするというだけでは駄目で、バイト長を考慮しなくてはいけないようです。

Because it is troublesome, I set the upper limit of the length to 100 characters.
それは大変手間なので、100文字(100Char * 2B = 200 < 260)を上限にすることとしました。

Please do forgive me.
御了承ください。



By the way, I added "Save tags with translation." option.
また、"Save tags with translation."を追加しました。

This option works as follows.
以下のような動作になります。

3.0.4: 肉niku

3.0.5-on: 肉(niku) [default]
3.0.5-off: 肉

**Comment by ginzu** [comment]
?short-tags? means the tags less than 9 characters.
?short-tags?は８文字以下のタグすべてとなります。

**Comment by ginzu** [comment]
I released 3.0.5. Please try it.
修正してAMOに上げたので確認よろしくお願いします。
